site_name: 'Omeka Classic User Manual'
theme: 
    name: 'readthedocs'
    custom_dir: 'omeka/'
    include_homepage_in_sidebar: false
site_dir: 'html'
repo_url: 'https://github.com/omeka/classic-enduser'
extra_css: 
    - css/extra.css
markdown_extensions:
    - toc:
        permalink: ÔÉÅ
nav:
    - index.md
    - Getting Started:
        - GettingStarted/Site_Planning_Tips.md
        - GettingStarted/UsingOmeka.md
        - GettingStarted/Hosting_Suggestions.md
        - GettingStarted/Feature_List.md
        - GettingStarted/Accessibility_Statement.md
        - GettingStarted/Screencasts.md
        - GettingStarted/Searching.md
    - Installing:
        - Installation/System_Requirements.md
        - Installation/Installation.md
        - Installation/Upgrading.md
        - Installation/Configuring_Language.md
        - Installation/Setting_Directory_Permissions.md
    - Content:
        - Content/Items.md
        - Content/Files.md
        - Content/Working_with_Dublin_Core.md
        - Content/Using_HTML_Editor-TinyMCE.md
        - Content/Item_Types.md
        - Content/Collections.md
        - Content/Tags.md
        - Content/Shortcodes.md
    - Administration:
        - Admin/Adding_and_Managing_Plugins.md
        - Admin/Appearance/Themes.md
        - Admin/Appearance/Navigation.md
        - Admin/Appearance/Appearance_Settings.md
        - Admin/Users.md
        - Admin/Settings/General_Settings.md
        - Admin/Settings/Security_Settings.md
        - Admin/Settings/Search_Settings.md
        - Admin/Settings/Element_Sets.md
        - Admin/Settings/Item_Type_Elements.md
        - Admin/Settings/API_Settings.md
        - Admin/Settings/ReCaptcha.md
    - Plugins:
        - Plugins/Coins.md
        - Plugins/CollectionTree.md
        - Plugins/Commenting.md
        - Plugins/Contribution.md
        - Plugins/CSS_Editor.md
        - Plugins/CSV_Import.md
        - Plugins/DerivativeImages.md
        - Plugins/DocsViewer.md
        - Plugins/Dropbox.md
        - Plugins/DublinCoreExtended.md
        - Plugins/Editorial.md
        - Plugins/EmbedCodes.md
        - Plugins/ExhibitBuilder.md
        - Plugins/ExhibitImageAnnotation.md
        - Plugins/Geolocation.md
        - Plugins/GuestUser.md
        - Plugins/Heist.md
        - Plugins/ItemOrder.md
        - Plugins/ItemRelations.md
        - Plugins/Library_of_Congress_Suggest.md
        - Plugins/Ngram.md
        - Plugins/OaipmhHarvester.md
        - Plugins/OaiPmhRepository.md
        - Plugins/Omeka_API_Import.md
        - Plugins/PBCore.md
        - Plugins/PdfText.md
        - Plugins/Plugin_Shortcodes.md
        - Plugins/Posters.md
        - Plugins/RecordRelations.md
        - Plugins/RedactElements.md
        - Plugins/Reports.md
        - Plugins/Scripto.md
        - Plugins/SearchByMetadata.md
        - Plugins/ShortcodeCarousel.md
        - Plugins/SimpleContactForm.md
        - Plugins/SimplePages.md
        - Plugins/SimpleVocab.md
        - Plugins/SocialBookmarking.md
        - Plugins/TextAnalysis.md
        - Plugins/TextAnnotation.md
        - Plugins/UserProfiles.md
        - Plugins/VRACore.md
        - Plugins/ZoomIt.md
        - Plugins/ZoteroImport.md
    - Troubleshooting: 
        - Troubleshooting/Troubleshooting_Omeka.md
        - Troubleshooting/Retrieving_Error_Messages.md
        - Troubleshooting/Report-a-bug.md
    - Technical:
        - Technical/Adding_LightBox_to_Omeka.md
        - Technical/Backing_up_an_Omeka_Database.md
        - Technical/Configuring_File_Storage.md
        - Technical/ConfiguringThumbnailCreation.md
        - Technical/Contribute_Code_to_Omeka.md
        - Technical/DatabaseConfigurationFile.md
        - Technical/Legacy_documentation.md
        - Technical/Moving_to_Another_Server.md
        - Technical/Output_Formats.md
        - Technical/Setting_PHP_Path.md
        - Technical/Translate_Omeka.md
        - Technical/Using_Omeka_with_Other_Tools_and_Platforms.md
